### ISSUE TITLE
XDP-based network policy perf test

### ISSUE THREAD

**Issue by XiaoningDing** [CentaurusInfra/mizar#374]
Perf test:

1) Overhead of Mizar network policy implementation (CPU, memory).
2) Supported PPS and throughput.

### Subtasks ###
- [ ] deploy Mizar cni plugin to K8S test env (1+2 EC2 VM based)
- [ ] collect base line of cpu/mem/throughput/pps with release 0.6
- [ ] collect perf data of cpu/mem/throughput/pps with network policy feature (1 ingress rule + 1 egress rule)
- [ ] prepare overhead report
